-- ---------------------------------------------------------------------------
-- V1: the original TaskFlow schema - projects and their tasks.
--
-- Written in SQL that H2 2.x and PostgreSQL 14+ both accept, so dev and prod
-- run the identical migration set (see README, "Database migrations"):
--   * BIGINT GENERATED BY DEFAULT AS IDENTITY - SQL standard identity columns,
--     supported by H2 2.x and PostgreSQL 10+ (avoids Postgres-only SERIAL and
--     H2-only AUTO_INCREMENT).
--   * TIMESTAMP(6) WITH TIME ZONE - what Hibernate maps java.time.Instant to on
--     both dialects, which matters because JPA runs with ddl-auto: validate.
-- ---------------------------------------------------------------------------

CREATE TABLE projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(150) NOT NULL,
    description VARCHAR(2000),
    status      VARCHAR(20) NOT NULL,
    priority    VARCHAR(20) NOT NULL,
    due_date    DATE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    project_id  BIGINT NOT NULL,
    CONSTRAINT fk_tasks_project FOREIGN KEY (project_id)
        REFERENCES projects (id) ON DELETE CASCADE
);

-- Supports the /api/tasks?projectId= filter and the FK itself.
CREATE INDEX idx_tasks_project_id ON tasks (project_id);

-- Supports the /api/tasks?status= filter.
CREATE INDEX idx_tasks_status ON tasks (status);
