-- ---------------------------------------------------------------------------
-- V2: accounts, and the ownership link that scopes every project to one user.
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(254) NOT NULL,
    -- BCrypt digest, never the plaintext password.
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- Added nullable first, which is the shape this migration would take against a
-- database that already had projects in it: add the column, backfill an owner
-- for every existing row, then tighten the constraint. TaskFlow has never been
-- deployed with data, so the backfill step is a no-op and the SET NOT NULL below
-- succeeds immediately. Against a populated table it would fail loudly instead
-- of silently inventing an owner, which is the behaviour we want.
ALTER TABLE projects ADD COLUMN owner_id BIGINT;

-- (backfill would go here)

ALTER TABLE projects ALTER COLUMN owner_id SET NOT NULL;

ALTER TABLE projects ADD CONSTRAINT fk_projects_owner
    FOREIGN KEY (owner_id) REFERENCES users (id);

-- Every project read is filtered by owner_id, so this index is on the hot path.
CREATE INDEX idx_projects_owner_id ON projects (owner_id);
